/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import Cadastros.ConnectionFactory;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author Lucas
 */
public class TelaResenhasJaCadastradas extends javax.swing.JFrame {

    /**
     * Creates new form TelaResenhasJaCadastradas
     */
    public TelaResenhasJaCadastradas() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnvoltar = new javax.swing.JButton();
        btnavancar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        btnvoltar.setText("Voltar");
        btnvoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnvoltarActionPerformed(evt);
            }
        });
        getContentPane().add(btnvoltar);
        btnvoltar.setBounds(680, 430, 75, 23);

        btnavancar.setText("Adicionar Lista");
        btnavancar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnavancarActionPerformed(evt);
            }
        });
        getContentPane().add(btnavancar);
        btnavancar.setBounds(30, 430, 120, 20);

        jScrollPane1.setViewportView(jList1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(170, 70, 370, 380);

        jLabel1.setText("Lista de Livros Cadastrados");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(270, 20, 190, 40);

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void FillListbox() {

    DefaultListModel m = new DefaultListModel();
    String sql = "SELECT * FROM livros";
    try {
        ConnectionFactory factory = new ConnectionFactory();
        Connection c = factory.obtemConexao();

        while (factory.next()) {
            String titulo = factory.getString("titulo");
            if (titulo != null && !titulo.isEmpty()) {
                m.addElement(titulo);
            } else {
                m.addElement("");
            }
        }
        c.close();

    } catch (Exception e) {
        JOptionPane.showMessageDialog(null, e);
    } finally {
    }
}
    private void btnvoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnvoltarActionPerformed
        // TODO add your handling code here:
        TelaInicial dt = new TelaInicial();
            dt.setVisible(true);
            this.dispose();
    }//GEN-LAST:event_btnvoltarActionPerformed

    private void btnavancarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnavancarActionPerformed
         // Replace the placeholder code with the actual database connection and data retrieval logic
    DefaultListModel m = new DefaultListModel();
    try {
        // Establish connection to the database
        ConnectionFactory factory = new ConnectionFactory();
        Connection c = factory.obtemConexao();

        // Execute the SQL query to retrieve book titles
        String sql = "SELECT titulo FROM livros";
        Statement statement = c.createStatement();
        ResultSet rs = statement.executeQuery(sql);

        // Add retrieved book titles to the list model
        while (rs.next()) {
            String titulo = rs.getString("titulo");
            m.addElement(titulo);
        }

        // Close database resources
        rs.close();
        statement.close();
        c.close();
    } catch (Exception e) {
        e.printStackTrace();
    }

    // Set the modified list model to the JList
    jList1.setModel(m);
            

        
    }//GEN-LAST:event_btnavancarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaResenhasJaCadastradas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaResenhasJaCadastradas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaResenhasJaCadastradas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaResenhasJaCadastradas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaResenhasJaCadastradas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnavancar;
    private javax.swing.JButton btnvoltar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JList<String> jList1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

    private DefaultListModel newDefaultListModel() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
}
