/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import Cadastros.Usuario;
import Cadastros.ConnectionFactory;
import javax.swing.JOptionPane;

/**
 *
 * @author erica
 */
public class TelaLogin extends javax.swing.JFrame {

    /**
     * Creates new form CadastroUsuario
     */
    public TelaLogin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtTipoUsu = new javax.swing.JTextField();
        btnLogar = new javax.swing.JButton();
        btnSair = new javax.swing.JButton();
        ckSenha = new javax.swing.JCheckBox();
        txtSenha = new javax.swing.JPasswordField();
        jLabel2 = new javax.swing.JLabel();
        txtEmail1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Tela Login");
        setType(java.awt.Window.Type.POPUP);
        getContentPane().setLayout(null);

        txtTipoUsu.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtTipoUsu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTipoUsuActionPerformed(evt);
            }
        });
        getContentPane().add(txtTipoUsu);
        txtTipoUsu.setBounds(240, 290, 50, 30);

        btnLogar.setText("Logar");
        btnLogar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogarActionPerformed(evt);
            }
        });
        getContentPane().add(btnLogar);
        btnLogar.setBounds(150, 350, 100, 35);

        btnSair.setText("Sair");
        getContentPane().add(btnSair);
        btnSair.setBounds(290, 350, 100, 35);

        ckSenha.setText("Mostrar senha");
        ckSenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ckSenhaActionPerformed(evt);
            }
        });
        getContentPane().add(ckSenha);
        ckSenha.setBounds(210, 230, 119, 20);

        txtSenha.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtSenhaFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtSenhaFocusLost(evt);
            }
        });
        txtSenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSenhaActionPerformed(evt);
            }
        });
        getContentPane().add(txtSenha);
        txtSenha.setBounds(190, 190, 160, 38);

        jLabel2.setText("Tipo de Usuário");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(220, 270, 90, 20);

        txtEmail1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtEmail1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmail1ActionPerformed(evt);
            }
        });
        getContentPane().add(txtEmail1);
        txtEmail1.setBounds(190, 100, 160, 38);

        jLabel3.setText("CPF");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(250, 70, 30, 20);

        jLabel4.setText("SENHA");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(240, 160, 60, 20);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtTipoUsuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTipoUsuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTipoUsuActionPerformed

    private void btnLogarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogarActionPerformed
        // TODO add your handling code here:
        
        Usuario usu = new Usuario();
        
        String cpf = txtEmail1.getText();
        String senha = txtSenha.getText();
        
        
   
        int resp = usu.ValidarSenha(cpf, senha);  

        //JOptionPane.showMessageDialog(null,"resp - " + resp);
        
        if(txtTipoUsu.getText().equals("1")){
            TelaAdmin dt = new TelaAdmin();
            dt.setVisible(true);
            this.dispose();
            
            
            
        }
        
        else{
            TelaInicial dt = new TelaInicial();
            dt.setVisible(true);
            this.dispose();
        }
  
        
    }//GEN-LAST:event_btnLogarActionPerformed

    private void ckSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ckSenhaActionPerformed
        // TODO add your handling code here:
        if (ckSenha.isSelected())
        {
            txtSenha.setEchoChar((char)0);
        }
        else
        {
            txtSenha.setEchoChar('*');
        }
        
        
        
        
        
        
        
        
    }//GEN-LAST:event_ckSenhaActionPerformed

    private void txtSenhaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtSenhaFocusGained
        // TODO add your handling code here:
          if (txtSenha.getText().equals(""))
          {   
             txtSenha.setText("");
          }   
    }//GEN-LAST:event_txtSenhaFocusGained

    private void txtSenhaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtSenhaFocusLost
        // TODO add your handling code here:
        if (txtSenha.getText().equals(""))
        {
            txtSenha.setText("Digite uma Senha");
        }
    }//GEN-LAST:event_txtSenhaFocusLost

    private void txtSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSenhaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSenhaActionPerformed

    private void txtEmail1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmail1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmail1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogar;
    private javax.swing.JButton btnSair;
    private javax.swing.JCheckBox ckSenha;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField txtEmail1;
    private javax.swing.JPasswordField txtSenha;
    private javax.swing.JTextField txtTipoUsu;
    // End of variables declaration//GEN-END:variables
}
