/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import Cadastros.ConnectionFactory;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.ListModel;

/**
 *
 * @author paulo
 */
public class TelaInicial extends javax.swing.JFrame {

    /**
     * Creates new form TelaInicial
     */
    public TelaInicial() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnCadastro = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList2 = new javax.swing.JList<>();
        jButton1 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        menuCadastrarLivro = new javax.swing.JMenuItem();
        menuFazerResenha = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        btnCadastro.setText("Cadastrar");
        btnCadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastroActionPerformed(evt);
            }
        });
        getContentPane().add(btnCadastro);
        btnCadastro.setBounds(490, 30, 90, 23);

        jScrollPane1.setViewportView(jList2);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(380, 220, 460, 210);

        jButton1.setText("Atualizar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(250, 220, 100, 23);

        jMenu1.setText("Menu");

        menuCadastrarLivro.setText("Ver resenha.");
        menuCadastrarLivro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuCadastrarLivroActionPerformed(evt);
            }
        });
        jMenu1.add(menuCadastrarLivro);

        menuFazerResenha.setText("Fazer resenha.");
        menuFazerResenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuFazerResenhaActionPerformed(evt);
            }
        });
        jMenu1.add(menuFazerResenha);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Sair");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

   
    
    
    private void menuCadastrarLivroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuCadastrarLivroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuCadastrarLivroActionPerformed

    private void menuFazerResenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuFazerResenhaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuFazerResenhaActionPerformed

    private void btnCadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastroActionPerformed
        // TODO add your handling code here:
        TelaResenha dt = new TelaResenha();
            dt.setVisible(true);
            this.dispose();
    }//GEN-LAST:event_btnCadastroActionPerformed

     private void FillListbox() {

    DefaultListModel m = new DefaultListModel();
    String sql = "SELECT * FROM livros";
    try {
        ConnectionFactory factory = new ConnectionFactory();
        Connection c = factory.obtemConexao();

        while (factory.next()) {
            String titulo = factory.getString("titulo");
            if (titulo != null && !titulo.isEmpty()) {
                m.addElement(titulo);
            } else {
                m.addElement("");
            }
        }
        c.close();

    } catch (Exception e) {
        JOptionPane.showMessageDialog(null, e);
    } finally {
    }
}
    
 
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
              // TODO add your handling code here:
              DefaultListModel m = new DefaultListModel();
    try {
    // Estabelecer conexão com o banco de dados
    ConnectionFactory factory = new ConnectionFactory();
    Connection c = factory.obtemConexao();

    // Executar a consulta SQL para recuperar os títulos dos livros
    String sql = "SELECT titulo FROM livros";
    Statement statement = c.createStatement();
    ResultSet rs = statement.executeQuery(sql);

    // Adicionar os títulos dos livros ao modelo da lista
    while (rs.next()) {
        String titulo = rs.getString("titulo");
        m.addElement(titulo);
    }

    // Fechar os recursos do banco de dados
    rs.close();
    statement.close();
    c.close();
} catch (SQLException e) {
    e.printStackTrace();
}

// Definir o modelo modificado da lista no JList
jList2.setModel(m);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaInicial().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCadastro;
    private javax.swing.JButton jButton1;
    private javax.swing.JList<String> jList2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JMenuItem menuCadastrarLivro;
    private javax.swing.JMenuItem menuFazerResenha;
    // End of variables declaration//GEN-END:variables
}
