/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.interface1.java;

/**
 
 * @author Lucas
 */
import javax.swing.JOptionPane;
public class login extends javax.swing.JFrame {

    /**
     * Creates new form login
     */
    public login()  {
        initComponents();
     
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        botaoTextField = new javax.swing.JButton();
        senhaPasswordField = new javax.swing.JPasswordField();
        loginTextField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        botaoTextField.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/interface1/java/Design sem nome.png"))); // NOI18N
        botaoTextField.setText("jButton1");
        botaoTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoTextFieldActionPerformed(evt);
            }
        });
        getContentPane().add(botaoTextField);
        botaoTextField.setBounds(300, 180, 30, 20);

        senhaPasswordField.setText("jPasswordField1");
        senhaPasswordField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                senhaPasswordFieldActionPerformed(evt);
            }
        });
        getContentPane().add(senhaPasswordField);
        senhaPasswordField.setBounds(130, 180, 160, 20);

        loginTextField.setText("Digite seu E-mail");
        loginTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginTextFieldActionPerformed(evt);
            }
        });
        getContentPane().add(loginTextField);
        loginTextField.setBounds(130, 120, 160, 20);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/interface1/java/Arquimedes (2).png"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 400, 300);

        pack();
    }// </editor-fold>                        

    private void botaoTextFieldActionPerformed(java.awt.event.ActionEvent evt) {                                               
        String txtLogin = loginTextField.getText(); 
                        
        String txtSenha = new String(senhaPasswordField.getPassword()); 
       
     if (txtLogin.equals("admin ") && (txtSenha.equals("1,2,3"))){
         JOptionPane.showMessageDialog(null, "login com sucesso");
     } 
     else {
         JOptionPane.showMessageDialog(null, "login errado"); 
     }
     
    }                                              

    private void loginTextFieldActionPerformed(java.awt.event.ActionEvent evt) {                                               
        // TODO add your handling code here:
    }                                              

    private void senhaPasswordFieldActionPerformed(java.awt.event.ActionEvent evt) {                                                   
      String txtLogin = loginTextField.getText(); 
        String txtSenha = new String(senhaPasswordField.getPassword()); 
        JOptionPane.showMessageDialog(null,"Login:" + txtLogin + "senha" + txtSenha);     
    }                                                  

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton botaoTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField loginTextField;
    private javax.swing.JPasswordField senhaPasswordField;
    // End of variables declaration                   
}
