/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import Cadastros.Pessoa;
import Cadastros.Usuario;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author vanderlei
 */
public class CadastroUsuario extends javax.swing.JFrame {

    /**
     * Creates new form CadastroUsuario
     */
    public CadastroUsuario() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtNome = new javax.swing.JTextField();
        txtCPF = new javax.swing.JTextField();
        txtTipoUsu = new javax.swing.JTextField();
        chkshowpassword = new javax.swing.JCheckBox();
        lblNome = new javax.swing.JLabel();
        lblEmail = new javax.swing.JLabel();
        lblUsuario = new javax.swing.JLabel();
        lblSenha = new javax.swing.JLabel();
        lblTipoUsu = new javax.swing.JLabel();
        lblFundo = new javax.swing.JLabel();
        txtSenha = new javax.swing.JPasswordField();
        txtEmail = new javax.swing.JTextField();
        lblIdade = new javax.swing.JLabel();
        txtIdade = new javax.swing.JTextField();
        lblSexo = new javax.swing.JLabel();
        txtSexo = new javax.swing.JTextField();
        jBtnVoltar = new javax.swing.JButton();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        btIncluir = new javax.swing.JMenuItem();
        btConsultar = new javax.swing.JMenuItem();
        btExcluir = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);
        getContentPane().add(txtNome);
        txtNome.setBounds(50, 110, 352, 30);

        txtCPF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCPFActionPerformed(evt);
            }
        });
        getContentPane().add(txtCPF);
        txtCPF.setBounds(50, 40, 352, 30);
        getContentPane().add(txtTipoUsu);
        txtTipoUsu.setBounds(180, 460, 90, 22);

        chkshowpassword.setText("Mostrar senha");
        chkshowpassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkshowpasswordActionPerformed(evt);
            }
        });
        getContentPane().add(chkshowpassword);
        chkshowpassword.setBounds(50, 400, 190, 20);

        lblNome.setFont(new java.awt.Font("Yu Gothic", 1, 18)); // NOI18N
        lblNome.setForeground(java.awt.Color.white);
        lblNome.setText("Nome");
        getContentPane().add(lblNome);
        lblNome.setBounds(180, 80, 140, 30);

        lblEmail.setFont(new java.awt.Font("Yu Gothic", 1, 18)); // NOI18N
        lblEmail.setForeground(java.awt.Color.white);
        lblEmail.setText("CPF");
        getContentPane().add(lblEmail);
        lblEmail.setBounds(190, 20, 110, 24);

        lblUsuario.setFont(new java.awt.Font("Yu Gothic", 1, 18)); // NOI18N
        lblUsuario.setForeground(java.awt.Color.white);
        lblUsuario.setText("E-mail");
        getContentPane().add(lblUsuario);
        lblUsuario.setBounds(180, 270, 110, 40);

        lblSenha.setFont(new java.awt.Font("Yu Gothic", 1, 18)); // NOI18N
        lblSenha.setForeground(java.awt.Color.white);
        lblSenha.setText("Senha");
        getContentPane().add(lblSenha);
        lblSenha.setBounds(180, 350, 110, 30);

        lblTipoUsu.setFont(new java.awt.Font("Yu Gothic", 1, 14)); // NOI18N
        lblTipoUsu.setForeground(java.awt.Color.white);
        lblTipoUsu.setText("Tipo de usuário");
        getContentPane().add(lblTipoUsu);
        lblTipoUsu.setBounds(170, 430, 130, 30);
        getContentPane().add(lblFundo);
        lblFundo.setBounds(-30, -20, 220, 440);

        txtSenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSenhaActionPerformed(evt);
            }
        });
        getContentPane().add(txtSenha);
        txtSenha.setBounds(50, 380, 352, 22);
        getContentPane().add(txtEmail);
        txtEmail.setBounds(50, 310, 350, 30);

        lblIdade.setFont(new java.awt.Font("Yu Gothic", 1, 18)); // NOI18N
        lblIdade.setForeground(java.awt.Color.white);
        lblIdade.setText("Idade");
        getContentPane().add(lblIdade);
        lblIdade.setBounds(180, 150, 140, 30);
        getContentPane().add(txtIdade);
        txtIdade.setBounds(50, 180, 352, 30);

        lblSexo.setFont(new java.awt.Font("Yu Gothic", 1, 18)); // NOI18N
        lblSexo.setForeground(java.awt.Color.white);
        lblSexo.setText("Sexo");
        getContentPane().add(lblSexo);
        lblSexo.setBounds(180, 210, 140, 30);
        getContentPane().add(txtSexo);
        txtSexo.setBounds(50, 240, 352, 30);

        jBtnVoltar.setText("Voltar");
        jBtnVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnVoltarActionPerformed(evt);
            }
        });
        getContentPane().add(jBtnVoltar);
        jBtnVoltar.setBounds(330, 490, 72, 23);

        jMenu3.setText("Usuário");

        btIncluir.setText("Incluir");
        btIncluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btIncluirActionPerformed(evt);
            }
        });
        jMenu3.add(btIncluir);

        btConsultar.setText("Consultar");
        btConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btConsultarActionPerformed(evt);
            }
        });
        jMenu3.add(btConsultar);

        btExcluir.setText("Excluir");
        btExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btExcluirActionPerformed(evt);
            }
        });
        jMenu3.add(btExcluir);

        jMenuBar2.add(jMenu3);

        setJMenuBar(jMenuBar2);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void chkshowpasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkshowpasswordActionPerformed
        // TODO add your handling code here:
                if (chkshowpassword.isSelected())
        {
            txtSenha.setEchoChar((char)0);
        }
        else
        {
            txtSenha.setEchoChar('*');
        }
    }//GEN-LAST:event_chkshowpasswordActionPerformed

    private void Limpar()
    {
        txtCPF.setText("");
        txtNome.setText("");
        txtIdade.setText("");
        txtSexo.setText("");
        txtEmail.setText("");
        txtSenha.setText("");
        txtTipoUsu.setText("");   
    }
    
    
    
    private void btIncluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btIncluirActionPerformed
        // TODO add your handling code here:
        
        if (!"".equals(txtNome.getText()))
        {
            Usuario usu = new Usuario();
           
            usu.setCpf(txtCPF.getText());
            usu.setNome(txtNome.getText());
            usu.setIdade(txtIdade.getText());
            usu.setSexo(txtSexo.getText());
            usu.setEmail(txtEmail.getText());
            usu.setSenha(txtSenha.getText());
            usu.setTipoUsu(txtTipoUsu.getText());
            
        try {
          usu.inserir();          
          Limpar();   
          System.out.println("Atualizado com sucesso!!");
        } catch (SQLException ex) {
            Logger.getLogger(CadastroUsuario.class.getName()).log(Level.SEVERE, null, ex);
        }  
        }
        else
        {
            JOptionPane.showMessageDialog
                    (null,"Campos em branco, complete-os para poder incluir!!",
                            "Cadastro de Usuário", JOptionPane.ERROR_MESSAGE);
        }
        
    }//GEN-LAST:event_btIncluirActionPerformed

    private void btConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btConsultarActionPerformed

        // TODO add your handling code here:
        Usuario usu = new Usuario();
        
        usu.setCpf(txtCPF.getText());
        
        usu.Consultar();  
        
        txtNome.setText(usu.getNome());
        txtIdade.setText(usu.getIdade());
        txtSexo.setText(usu.getSexo());
        txtEmail.setText(usu.getEmail());
        //txtUsuario.setText("");
        txtSenha.setText(usu.getSenha());
        txtTipoUsu.setText(usu.getTipoUsu());   
        
    }//GEN-LAST:event_btConsultarActionPerformed

    private void txtCPFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCPFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCPFActionPerformed

    private void txtSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSenhaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSenhaActionPerformed

    private void btExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btExcluirActionPerformed
        // TODO add your handling code here:
        if (!"".equals(txtNome.getText()))
        {
            Pessoa ps = new Pessoa();
           
            ps.setCpf(txtCPF.getText());
            ps.setNome(txtNome.getText());
            ps.setIdade(txtIdade.getText());
            ps.setSexo(txtSexo.getText());
            ps.setEmail(txtEmail.getText());
            ps.setSenha(txtSenha.getText());
            ps.setTipoUsu(txtTipoUsu.getText());
            
            ps.apagar();
            Limpar(); 
            System.out.println("Apagado com sucesso!!");
        }
        else
        {
            JOptionPane.showMessageDialog
                    (null,"Campos em branco, complete-os para poder Excluir!!",
                            "Cadastro de Usuário", JOptionPane.ERROR_MESSAGE);
        }
        
    }//GEN-LAST:event_btExcluirActionPerformed

    private void jBtnVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnVoltarActionPerformed
        // TODO add your handling code here:
        
        TelaAdmin dt = new TelaAdmin();
            dt.setVisible(true);
            this.dispose();
    }//GEN-LAST:event_jBtnVoltarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastroUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastroUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastroUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastroUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastroUsuario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem btConsultar;
    private javax.swing.JMenuItem btExcluir;
    private javax.swing.JMenuItem btIncluir;
    private javax.swing.JCheckBox chkshowpassword;
    private javax.swing.JButton jBtnVoltar;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblFundo;
    private javax.swing.JLabel lblIdade;
    private javax.swing.JLabel lblNome;
    private javax.swing.JLabel lblSenha;
    private javax.swing.JLabel lblSexo;
    private javax.swing.JLabel lblTipoUsu;
    private javax.swing.JLabel lblUsuario;
    private javax.swing.JTextField txtCPF;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtIdade;
    private javax.swing.JTextField txtNome;
    private javax.swing.JPasswordField txtSenha;
    private javax.swing.JTextField txtSexo;
    private javax.swing.JTextField txtTipoUsu;
    // End of variables declaration//GEN-END:variables
}
