/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

/**
 *
 * @author paulo
 */
public class TelaResenha extends javax.swing.JFrame {

    /**
     * Creates new form TelaResenha
     */
    public TelaResenha() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnResenhaUp = new javax.swing.JButton();
        btnResenhaDown = new javax.swing.JButton();
        txtAreaResenha = new javax.swing.JScrollPane();
        txtCadastroResenha = new javax.swing.JTextArea();
        chkFav = new javax.swing.JCheckBox();
        txtCadastroLivro = new javax.swing.JTextField();
        btnvoltar = new javax.swing.JButton();
        btnavancar = new javax.swing.JButton();
        lblFundoResenha = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        btnResenhaUp.setIcon(new javax.swing.ImageIcon("C:\\Users\\Lucas\\Downloads\\InterfaceBiblioteca-main\\Imagens\\botaoLike.png")); // NOI18N
        btnResenhaUp.setText("jButton1");
        getContentPane().add(btnResenhaUp);
        btnResenhaUp.setBounds(500, 340, 80, 40);

        btnResenhaDown.setIcon(new javax.swing.ImageIcon("C:\\Users\\Lucas\\Downloads\\InterfaceBiblioteca-main\\Imagens\\botaoDislike.png")); // NOI18N
        btnResenhaDown.setText("jButton1");
        btnResenhaDown.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResenhaDownActionPerformed(evt);
            }
        });
        getContentPane().add(btnResenhaDown);
        btnResenhaDown.setBounds(770, 340, 80, 40);

        txtCadastroResenha.setColumns(20);
        txtCadastroResenha.setRows(5);
        txtAreaResenha.setViewportView(txtCadastroResenha);

        getContentPane().add(txtAreaResenha);
        txtAreaResenha.setBounds(10, 120, 410, 360);

        chkFav.setText("Sim");
        getContentPane().add(chkFav);
        chkFav.setBounds(200, 70, 43, 20);

        txtCadastroLivro.setText("jTextField1");
        txtCadastroLivro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCadastroLivroActionPerformed(evt);
            }
        });
        getContentPane().add(txtCadastroLivro);
        txtCadastroLivro.setBounds(610, 90, 280, 50);

        btnvoltar.setIcon(new javax.swing.ImageIcon("C:\\Users\\Lucas\\Downloads\\InterfaceBiblioteca-main\\Imagens\\botaovoltar.png")); // NOI18N
        btnvoltar.setText("jButton1");
        getContentPane().add(btnvoltar);
        btnvoltar.setBounds(680, 473, 80, 20);

        btnavancar.setIcon(new javax.swing.ImageIcon("C:\\Users\\Lucas\\Downloads\\InterfaceBiblioteca-main\\Imagens\\botaoavancar.png")); // NOI18N
        btnavancar.setText("jButton2");
        getContentPane().add(btnavancar);
        btnavancar.setBounds(770, 473, 70, 20);

        lblFundoResenha.setIcon(new javax.swing.ImageIcon("C:\\Users\\Lucas\\Downloads\\InterfaceBiblioteca-main\\Imagens\\fundoResenha.png")); // NOI18N
        lblFundoResenha.setText("jLabel1");
        getContentPane().add(lblFundoResenha);
        lblFundoResenha.setBounds(0, 0, 1000, 500);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtCadastroLivroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCadastroLivroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCadastroLivroActionPerformed

    private void btnResenhaDownActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResenhaDownActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnResenhaDownActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaResenha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaResenha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaResenha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaResenha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaResenha().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnResenhaDown;
    private javax.swing.JButton btnResenhaUp;
    private javax.swing.JButton btnavancar;
    private javax.swing.JButton btnvoltar;
    private javax.swing.JCheckBox chkFav;
    private javax.swing.JLabel lblFundoResenha;
    private javax.swing.JScrollPane txtAreaResenha;
    private javax.swing.JTextField txtCadastroLivro;
    private javax.swing.JTextArea txtCadastroResenha;
    // End of variables declaration//GEN-END:variables
}
